### ISSUE TITLE
Latest update crashes on Raspberry Pi 5

### ISSUE THREAD

**Issue by XenoSlug** [flathub/io.github.theforceengine.tfe#12]
The latest update as of remote-info "a3915ed5d2060c46d18a6eb220f5697328e2193aac275b7648e2935f2d11fd90" doesn't work on my Raspberry Pi 5 with Ubuntu 23.10. It crashes as soon as you click play.

I can get it to run by downgrading to previous version using the command "sudo flatpak update --commit=55688cee02eecc30d1dde9df5af1c097fecc840ef53bdd3dc009b11fb6444c61 io.github.theforceengine.tfe" and than it works fine.

Classic (Software) rendering works fine, but GPU / OpenGL also crashes on Pi 5 unless launched with "flatpak run --env=MESA_GL_VERSION_OVERRIDE=3.3 io.github.theforceengine.tfe" and than the fps is alot lower than Classic.

**Comment by fpiesche** [comment]
Thanks for the info @JakeSmarter!
