### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Kirtai** [flathub/io.github.theforceengine.tfe#13]
[Version 1.10.000](https://github.com/luciusDXL/TheForceEngine/releases/tag/v1.10.000) has been released.

**Comment by fpiesche** [comment]
Flathub should pick this up and kick off a test build automatically soon. It's very late here - if the update hasn't arrived in a PR here yet by tomorrow morning I'll manually update then :)

**Comment by axredneck** [comment]
@fpiesche any news?

**Comment by fpiesche** [comment]
[PR is now open](https://github.com/flathub/io.github.theforceengine.tfe/pull/14). Sorry about this, $DAYJOB has been extremely crunchy and I've not had much energy to look at personal github stuff.

Hopefully the PR should also fix the crashes people have been experiencing in the Flatpak build, and the Flathub-side check for new releases. Will test before publishing once a test build has gone through...
